### ISSUE TITLE
Site Root versus Julie's portfolio

### ISSUE THREAD

**Issue by RickCogley** [juliecogley/julie_portfolio#3]
サイトルート：

`https://julie.cogley.jp`

...は、@juliecogley について、であるべき、簡単でも。現在中原さまのポートフォリオはルートに乗っているので、中原さまのサイトに見える。こう言う構成がおすすめ：

```
https://julie.cogley.jp/index.html   << 珠里ちゃんのかんたんなプロフィール、時間なければ「Coming Soon!」でもＯＫ
https://julie.cogley.jp/portfolio/nakahara/index.html  << 現在のルートのIndex
https://julie.cogley.jp/portfolio/nakahara/works/index.html   << 現在のworks.html
```

是非検討を

**Comment by juliecogley** [comment]
ありがとう！私自身のポートフォリオサイトを作成する時に、自分のプロフィール→なみのポートフォリオサイトの順番で掲載した方がいいってことだよね？

あと、無事に、googleformも挿入できました。

**Comment by RickCogley** [comment]
結局そう。自分のＵＲＬなので、人の為に作ったサイトはワントピックとして有るべきで、主となるのはあなたのサイト。
